
workflows:
  flutter-app:
    name: Build Flutter App for Android, iOS and Web
    max_build_duration: 20
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Build Web
        script: flutter build web
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/web/**/*
